semi final

diff --git a/tabfunc/tabdrp b/tabfunc/tabdrp
--- a/tabfunc/tabdrp
+++ b/tabfunc/tabdrp
@@ -1,10 +1,11 @@
 #!/bin/bash
-  echo -e "Enter Table Name: \c"
-  read tName
-  rm $tName .$tName 2>/dev/null
-  if [[ $? == 0 ]]
-  then
+  read -p "Enter Table Name: " tabname
+  read -p "Enter y to remove $tabname :" inp
+  if [[ "y" == "$inp" ]]; then
+  rm -r $tabname .$tabname.meta 2>/dev/null
+  fi
+  if [[ $? == 0 ]]; then
     echo "Table Dropped Successfully"
   else
-    echo "Error Dropping Table $tName"
+    echo "Error Dropping Table $tabname"
   fi
diff --git a/tabfunc/tabins b/tabfunc/tabins
--- a/tabfunc/tabins
+++ b/tabfunc/tabins
@@ -1,54 +1,54 @@
 #!/bin/bash
   echo -e "Table Name: \c"
-  read tableName
-  if ! [[ -f $tableName ]]; then
-    echo "Table $tableName isn't existed ,choose another Table"
+  read tabname
+  if ! [[ -f $tabname ]]; then
+    echo "Table $tabname isn't existed ,choose another Table"
     tablesMenu
   fi
-  colsNum=`awk 'END{print NR}' .$tableName`
+  colnum=`awk 'END{print NR}' .$tabname.meta`
   sep=":"
   rowsep="\n"
-  for (( i = 2; i <= $colsNum; i++ )); do
-    colName=$(awk 'BEGIN{FS=":"}{ if(NR=='$i') print $1}' .$tableName)
-    colType=$( awk 'BEGIN{FS=":"}{if(NR=='$i') print $2}' .$tableName)
-    colKey=$( awk 'BEGIN{FS=":"}{if(NR=='$i') print $3}' .$tableName)
-    echo -e "$colName ($colType) = \c"
+  for (( i = 2; i <= $colnum; i++ )); do
+    colname=$(awk 'BEGIN{FS=":"}{ if(NR=='$i') print $1}' .$tabname.meta)
+    coltype=$( awk 'BEGIN{FS=":"}{if(NR=='$i') print $2}' .$tabname.meta)
+    colKey=$( awk 'BEGIN{FS=":"}{if(NR=='$i') print $3}' .$tabname.meta)
+    echo -e "$colname ($coltype) = \c"
     read data
 
     # Validate Input
-    if [[ $colType == "int" ]]; then
+    if [[ $coltype == "int" ]]; then
       while ! [[ $data =~ ^[0-9]*$ ]]; do
         echo -e "invalid DataType !!"
-        echo -e "$colName ($colType) = \c"
+        echo -e "$colname ($coltype) = \c"
         read data
       done
     fi
 
     if [[ $colKey == "PK" ]]; then
       while [[ true ]]; do
-        if [[ $data =~ ^[`awk 'BEGIN{FS=":" ; ORS=" "}{if(NR != 1)print $(('$i'-1))}' $tableName`]$ ]]; then
+        if [[ $data =~ ^[`awk 'BEGIN{FS=":" ; ORS=" "}{if(NR != 1)print $(('$i'-1))}' $tabname`]$ ]]; then
           echo -e "invalid input for Primary Key !!"
         else
           break;
         fi
-        echo -e "$colName ($colType) = \c"
+        echo -e "$colname ($coltype) = \c"
         read data
       done
     fi
 
     #Set row
-    if [[ $i == $colsNum ]]; then
+    if [[ $i == $colnum ]]; then
       row=$row$data$rowsep
     else
       row=$row$data$sep
     fi
   done
-  echo -e $row"\c" >> $tableName
+  echo -e $row"\c" >> $tabname
   if [[ $? == 0 ]]
   then
     echo "Data Inserted Successfully"
   else
-    echo "Error Inserting Data into Table $tableName"
+    echo "Error Inserting Data into Table $tabname"
   fi
   row=""
   tablesMenu
