commit 1

diff --git a/tabfunc/tabsel b/tabfunc/tabsel
--- a/tabfunc/tabsel
+++ b/tabfunc/tabsel
@@ -1,50 +1,26 @@
 #!/bin/bash
 
-function selectMenu {
-  echo -e "\n\n+---------------Select Menu--------------------+"
-  echo "| 1. Select All Columns of a Table              |"
-  echo "| 2. Select Specific Column from a Table        |"
-  echo "| 3. Select From Table under condition          |"
-  echo "| 4. Aggregate Function for a Specific Column   |"
-  echo "| 5. Back To Tables Menu                        |"
-  echo "| 6. Back To Main Menu                          |"
-  echo "| 7. Exit                                       |"
-  echo "+----------------------------------------------+"
-  echo -e "Enter Choice: \c"
-  read ch
-  case $ch in
-    1) selectAll ;;
-    2) selectCol ;;
+select col in "Select All Columns of a Table" "Select Specific Column from a Table" "Select From Table under condition" "Back To Tables Menu" "Back To Main Menu" "Exit"
+do
+  case $REPLY in
+    1)  read -p "Enter Table Name: " tName
+        column -t -s ':' $tName 2>/dev/null
+        if [[ $? != 0 ]]; then
+        echo "Error Displaying Table $tName"
+        fi;;
+    2)  read -p "Enter Table Name: " tName 
+        read -p "Enter Column Number: " colNum
+        awk 'BEGIN{FS=":"}{print $'$colNum'}' $tName ;;
     3) clear; selectCon ;;
-    4) ;;
-    5) clear; tablesMenu ;;
-    6) clear; cd ../.. 2>>./.error.log; mainMenu ;;
-    7) exit ;;
+    4) clear; tablesMenu ;;
+    5) clear; cd ../.. 2>/dev/null; mainMenu ;;
+    6) exit ;;
     *) echo " Wrong Choice " ; selectMenu;
   esac
-}
-
-function selectAll {
-  echo -e "Enter Table Name: \c"
-  read tName
-  column -t -s '|' $tName 2>>./.error.log
-  if [[ $? != 0 ]]
-  then
-    echo "Error Displaying Table $tName"
-  fi
-  selectMenu
-}
-
-function selectCol {
-  echo -e "Enter Table Name: \c"
-  read tName
-  echo -e "Enter Column Number: \c"
-  read colNum
-  awk 'BEGIN{FS=":"}{print $'$colNum'}' $tName
-  selectMenu
-}
+done
 
 function selectCon {
+  
   echo -e "\n\n+--------Select Under Condition Menu-----------+"
   echo "| 1. Select All Columns Matching Condition    |"
   echo "| 2. Select Specific Column Matching Condition|"
@@ -58,7 +34,7 @@ function selectCon {
     1) clear; allCond ;;
     2) clear; specCond ;;
     3) clear; selectCon ;;
-    4) clear; cd ../.. 2>>./.error.log; mainMenu ;;
+    4) clear; cd ../.. 2>/dev/null; mainMenu ;;
     5) exit ;;
     *) echo " Wrong Choice " ; selectCon;
   esac
@@ -66,29 +42,27 @@ function selectCon {
 
 function allCond {
   echo -e "Select all columns from TABLE Where FIELD(OPERATOR)VALUE \n"
-  echo -e "Enter Table Name: \c"
-  read tName
-  echo -e "Enter required FIELD name: \c"
-  read field
+  read -p "Enter Table Name: " tName 
+  read -p "Enter required FIELD name: \c" field
+   
   fid=$(awk 'BEGIN{FS=":"}{if(NR==1){for(i=1;i<=NF;i++){if($i=="'$field'") print i}}}' $tName)
   if [[ $fid == "" ]]
   then
     echo "Not Found"
     selectCon
   else
-    echo -e "\nSupported Operators: [==, !=, >, <, >=, <=] \nSelect OPERATOR: \c"
-    read op
+    read -p "\nSupported Operators: [==, !=, >, <, >=, <=] \nSelect OPERATOR: \c" op
+    
     if [[ $op == "==" ]] || [[ $op == "!=" ]] || [[ $op == ">" ]] || [[ $op == "<" ]] || [[ $op == ">=" ]] || [[ $op == "<=" ]]
     then
-      echo -e "\nEnter required VALUE: \c"
-      read val
-      res=$(awk 'BEGIN{FS=":"}{if ($'$fid$op$val') print $0}' $tName 2>>./.error.log |  column -t -s '|')
+      read -p "\nEnter required VALUE: " val 
+      res=$(awk 'BEGIN{FS=":"}{if ($'$fid$op$val') print $0}' $tName 2>/dev/null |  column -t -s ':')
       if [[ $res == "" ]]
       then
         echo "Value Not Found"
         selectCon
       else
-        awk 'BEGIN{FS=":"}{if ($'$fid$op$val') print $0}' $tName 2>>./.error.log |  column -t -s '|'
+        awk 'BEGIN{FS=":"}{if ($'$fid$op$val') print $0}' $tName 2>/dev/null |  column -t -s ':'
         selectCon
       fi
     else
@@ -105,24 +79,22 @@ function specCond {
   echo -e "Enter required FIELD name: \c"
   read field
   fid=$(awk 'BEGIN{FS=":"}{if(NR==1){for(i=1;i<=NF;i++){if($i=="'$field'") print i}}}' $tName)
-  if [[ $fid == "" ]]
-  then
+  if [[ $fid == "" ]];  then
     echo "Not Found"
     selectCon
   else
     echo -e "\nSupported Operators: [==, !=, >, <, >=, <=] \nSelect OPERATOR: \c"
     read op
-    if [[ $op == "==" ]] || [[ $op == "!=" ]] || [[ $op == ">" ]] || [[ $op == "<" ]] || [[ $op == ">=" ]] || [[ $op == "<=" ]]
-    then
+    if [[ $op == "==" ]] || [[ $op == "!=" ]] || [[ $op == ">" ]] || [[ $op == "<" ]] || [[ $op == ">=" ]] || [[ $op == "<=" ]]; then
       echo -e "\nEnter required VALUE: \c"
       read val
-      res=$(awk 'BEGIN{FS=":"; ORS="\n"}{if ($'$fid$op$val') print $'$fid'}' $tName 2>>./.error.log |  column -t -s '|')
+      res=$(awk 'BEGIN{FS=":"; ORS="\n"}{if ($'$fid$op$val') print $'$fid'}' $tName 2>/dev/null |  column -t -s ':')
       if [[ $res == "" ]]
       then
         echo "Value Not Found"
         selectCon
       else
-        awk 'BEGIN{FS=":"; ORS="\n"}{if ($'$fid$op$val') print $'$fid'}' $tName 2>>./.error.log |  column -t -s '|'
+        awk 'BEGIN{FS=":"; ORS="\n"}{if ($'$fid$op$val') print $'$fid'}' $tName 2>/dev/null |  column -t -s ':'
         selectCon
       fi
     else
